grep -r 'सुवच' ../Data/allsutrani/*.htm > ../output/सुवच.html
grep -r 'चिन्त्य' ../Data/allsutrani/*.htm > ../output/चिन्त्य.html
grep -r 'विरुद्ध' ../Data/allsutrani/*.htm > ../output/विरुद्ध.html
grep -r 'केचि' ../Data/allsutrani/*.htm > ../output/केचिद्‌.html
grep -r 'अन्ये' ../Data/allsutrani/*.htm > ../output/अन्ये.html
grep -r 'परे' ../Data/allsutrani/*.htm > ../output/परे.html
grep -r 'वस्तुत' ../Data/allsutrani/*.htm > ../output/वस्तुतः.html
grep -r 'प्रमाणाभाव' ../Data/allsutrani/*.htm > ../output/प्रमाणाभाव.html
grep -r 'इतरे तु' ../Data/allsutrani/*.htm > ../output/इतरे.html
grep -r 'त्याहुः' ../Data/allsutrani/*.htm > ../output/इत्याहुः.html
grep -r 'प्रमाद' ../Data/allsutrani/*.htm > ../output/प्रमाद.html
grep -r 'प्रामादिक' ../Data/allsutrani/*.htm > ../output/प्रामादिक.html
grep -r 'स्खलित' ../Data/allsutrani/*.htm > ../output/स्खलित.html
grep -r 'इत्येके' ../Data/allsutrani/*.htm > ../output/इत्येके.html
grep -r 'एके' ../Data/allsutrani/*.htm > ../output/एके.html
grep -r 'मते' ../Data/allsutrani/*.htm > ../output/मते.html
grep -r 'विकल्प' ../Data/allsutrani/*.htm > ../output/विकल्प.html
grep -r 'वैकल्पिक' ../Data/allsutrani/*.htm > ../output/वैकल्पिक.html
grep -r 'आहुः' ../Data/allsutrani/*.htm > ../output/आहुः.html
grep -r 'त्वाहुः' ../Data/allsutrani/*.htm > ../output/त्वाहुः.html
grep -r 'प्राञ्च' ../Data/allsutrani/*.htm > ../output/प्राञ्च.html
grep -r 'उदीच' ../Data/allsutrani/*.htm > ../output/उदीच.html
grep -r 'मतान्तरे' ../Data/allsutrani/*.htm > ../output/मतान्तरे.html
grep -r 'पक्षे' ../Data/allsutrani/*.htm > ../output/पक्षे.html
grep -r 'कथंचि' ../Data/allsutrani/*.htm > ../output/कथंचित्‌.html
grep -r 'दरणीय' ../Data/allsutrani/*.htm > ../output/आदरणीय.html
grep -r 'पक्षान्तर' ../Data/allsutrani/*.htm > ../output/पक्षान्तर.html
grep -r 'कैश्चि' ../Data/allsutrani/*.htm > ../output/कैश्चिद्‌.html
grep -r 'दूषित' ../Data/allsutrani/*.htm > ../output/दूषित.html
grep -r 'शङ्क्य' ../Data/allsutrani/*.htm > ../output/शङ्क्य.html
grep -r 'शङ्क' ../Data/allsutrani/*.htm > ../output/शङ्का.html
grep -r 'वाच्य' ../Data/allsutrani/*.htm > ../output/वाच्य.html
grep -r 'शरण' ../Data/allsutrani/*.htm > ../output/शरण.html
grep -r 'सङ्गति' ../Data/allsutrani/*.htm > ../output/सङ्गति.html
grep -r 'पास्त' ../Data/allsutrani/*.htm > ../output/अपास्त.html
grep -r 'निरस्त' ../Data/allsutrani/*.htm > ../output/निरस्त.html
grep -r 'प्रत्याख्य' ../Data/allsutrani/*.htm > ../output/प्रत्याख्य.html
grep -r 'योगविभाग' ../Data/allsutrani/*.htm > ../output/योगविभाग.html
grep -r 'दोष' ../Data/allsutrani/*.htm > ../output/दोष.html
grep -r 'ग्रस्त' ../Data/allsutrani/*.htm > ../output/ग्रस्त.html
grep -r 'त्वाहुः' ../Data/allsutrani/*.htm > ../output/त्वाहुः.html
grep -r 'आकर' ../Data/allsutrani/*.htm > ../output/आकर.html
grep -r 'भाष्य' ../Data/allsutrani/*.htm > ../output/भाष्य.html
grep -r 'त्रिमुनि' ../Data/allsutrani/*.htm > ../output/त्रिमुनि.html
grep -r 'प्रमाण' ../Data/allsutrani/*.htm > ../output/प्रमाण.html
grep -r 'प्रामाणिक' ../Data/allsutrani/*.htm > ../output/प्रामाणिक.html
grep -r 'वदेत्' ../Data/allsutrani/*.htm > ../output/वदेत्.html
grep -r 'दिक्‌' ../Data/allsutrani/*.htm > ../output/दिक्‌.html
grep -r 'कुलेखक' ../Data/allsutrani/*.htm > ../output/कुलेखक.html
grep -r 'नवधान' ../Data/allsutrani/*.htm > ../output/अनवधान.html
grep -r 'हरदत्त' ../Data/allsutrani/*.htm > ../output/हरदत्त.html
grep -r 'अन्यत्र' ../Data/allsutrani/*.htm > ../output/अन्यत्र.html
grep -r 'साधु' ../Data/allsutrani/*.htm > ../output/साधु.html
grep -r 'कैयट' ../Data/allsutrani/*.htm > ../output/कैयट.html
grep -r 'अपाणिनीय' ../Data/allsutrani/*.htm > ../output/अपाणिनीय.html
grep -r 'दपाणिनीय' ../Data/allsutrani/*.htm > ../output/तदपाणिनीय.html
grep -r 'ज्ञापक' ../Data/allsutrani/*.htm > ../output/ज्ञापक.html
grep -r 'कुलेखक' ../Data/allsutrani/*.htm > ../output/कुलेखक.html
grep -r 'पाठान्तर' ../Data/allsutrani/*.htm > ../output/पाठान्तर.html
grep -r 'भिप्राय' ../Data/allsutrani/*.htm > ../output/अभिप्राय.html
grep -r 'दुष्ट' ../Data/allsutrani/*.htm > ../output/दुष्ट.html
grep -r 'दुष्य' ../Data/allsutrani/*.htm > ../output/दुष्य.html
grep -r 'विरोध' ../Data/allsutrani/*.htm > ../output/विरोध.html
grep -r 'दुर्घट' ../Data/allsutrani/*.htm > ../output/दुर्घट.html
grep -r 'दुर्लभ' ../Data/allsutrani/*.htm > ../output/दुर्लभ.html
grep -r 'तदसत्' ../Data/allsutrani/*.htm > ../output/तदसत्.html
grep -r 'सङ्गत' ../Data/allsutrani/*.htm > ../output/सङ्गत.html
grep -r 'असत्' ../Data/allsutrani/*.htm > ../output/असत्.html
grep -r 'व्याचक्ष' ../Data/allsutrani/*.htm > ../output/व्याचक्ष.html
grep -r 'निष्कर्ष' ../Data/allsutrani/*.htm > ../output/निष्कर्ष.html
grep -r 'तदयुक्त' ../Data/allsutrani/*.htm > ../output/तदयुक्त.html
grep -r 'स्पष्टार्थ' ../Data/allsutrani/*.htm > ../output/स्पष्टार्थ.html
grep -r 'वृत्तिकार' ../Data/allsutrani/*.htm > ../output/वृत्तिकार.html
grep -r 'वृत्तिकृ' ../Data/allsutrani/*.htm > ../output/वृत्तिकृद्‌.html
grep -r 'काशिकाकार' ../Data/allsutrani/*.htm > ../output/काशिकाकार.html
grep -r 'वामन' ../Data/allsutrani/*.htm > ../output/वामन.html
grep -r 'जयादित्य' ../Data/allsutrani/*.htm > ../output/जयादित्य.html
grep -r 'न्यासकार' ../Data/allsutrani/*.htm > ../output/न्यासकार.html
grep -r 'पदमञ्जरीकार' ../Data/allsutrani/*.htm > ../output/पदमञ्जरीकार.html
grep -r 'मनोरमाकार' ../Data/allsutrani/*.htm > ../output/मनोरमाकार.html
grep -r 'मनोरमायां' ../Data/allsutrani/*.htm > ../output/मनोरमायां.html
grep -r 'ब्देन्दुशेख' ../Data/allsutrani/*.htm > ../output/शब्देन्दुशेखर.html
grep -r 'कौमुद्या' ../Data/allsutrani/*.htm > ../output/कौमुद्या.html
grep -r 'कौमुदीकार' ../Data/allsutrani/*.htm > ../output/कौमुदीकार.html
grep -r 'दीक्षित' ../Data/allsutrani/*.htm > ../output/दीक्षित.html
grep -r 'जिनेन्द्र' ../Data/allsutrani/*.htm > ../output/जिनेन्द्र.html
grep -r 'वैयर्थ्य' ../Data/allsutrani/*.htm > ../output/वैयर्थ्य.html
grep -r 'वैयथ्र्य' ../Data/allsutrani/*.htm > ../output/वैयथ्र्य.html
grep -r 'शिष्ट' ../Data/allsutrani/*.htm > ../output/शिष्ट.html
grep -r 'पूर्वपक्ष' ../Data/allsutrani/*.htm > ../output/पूर्वपक्ष.html
grep -r 'वार्तिकविरोध' ../Data/allsutrani/*.htm > ../output/वार्तिकविरोध.html
grep -r 'सङ्गच्छ' ../Data/allsutrani/*.htm > ../output/सङ्गच्छ.html
grep -r 'कृतिगण' ../Data/allsutrani/*.htm > ../output/कृतिगण.html
grep -r 'व्यर्थ' ../Data/allsutrani/*.htm > ../output/व्यर्थ.html
grep -r 'त्याज्य' ../Data/allsutrani/*.htm > ../output/त्याज्य.html
grep -r 'भाष्ये तु' ../Data/allsutrani/*.htm > ../output/भाष्ये_तु.html
grep -r 'न दृश्यते' ../Data/allsutrani/*.htm > ../output/न_दृश्यते.html
grep -r 'प्रत्युदा' ../Data/allsutrani/*.htm > ../output/प्रत्युदा.html
grep -r 'भाष्यकार' ../Data/allsutrani/*.htm > ../output/भाष्यकार.html
grep -r 'भाष्यकृ' ../Data/allsutrani/*.htm > ../output/भाष्यकृत्‌.html
grep -r 'परिष्क' ../Data/allsutrani/*.htm > ../output/परिष्क.html
grep -r 'व्याख्येय' ../Data/allsutrani/*.htm > ../output/व्याख्येय.html
grep -r 'च्छन्त' ../Data/allsutrani/*.htm > ../output/इच्छन्ति.html
grep -r 'निन्द्य' ../Data/allsutrani/*.htm > ../output/निन्द्य.html
grep -r 'मानाभाव' ../Data/allsutrani/*.htm > ../output/मानाभाव.html
grep -r 'व्याख्यान्तर' ../Data/allsutrani/*.htm > ../output/व्याख्यान्तर.html
grep -r 'मन्य' ../Data/allsutrani/*.htm > ../output/मन्य.html
grep -r 'दुरुपपाद' ../Data/allsutrani/*.htm > ../output/दुरुपपाद.html
grep -r 'दुरुपपाद' ../Data/allsutrani/*.htm > ../output/दुरुपपाद.html
grep -r 'दूषयित' ../Data/allsutrani/*.htm > ../output/दूषयित.html
grep -r 'सिद्धान्तरत्नाक' ../Data/allsutrani/*.htm > ../output/सिद्धान्तरत्नाकर.html
grep -r 'ब्दरत्न' ../Data/allsutrani/*.htm > ../output/शब्दरत्न.html
grep -r 'प्रपञ्चित' ../Data/allsutrani/*.htm > ../output/प्रपञ्चित.html
grep -r 'स्तां ताव' ../Data/allsutrani/*.htm > ../output/आस्तां_तावत्.html
grep -r 'दुर्वच' ../Data/allsutrani/*.htm > ../output/दुर्वच.html
grep -r 'गौरव' ../Data/allsutrani/*.htm > ../output/गौरव.html
grep -r 'स्थित' ../Data/allsutrani/*.htm > ../output/स्थित.html
grep -r 'क्वचि' ../Data/allsutrani/*.htm > ../output/क्वचि.html
grep -r 'पुस्तक' ../Data/allsutrani/*.htm > ../output/पुस्तक.html
grep -r 'वक्तव्य' ../Data/allsutrani/*.htm > ../output/वक्तव्य.html
grep -r 'पेक्ष्य' ../Data/allsutrani/*.htm > ../output/पेक्ष्य.html
grep -r 'त्यक्तुं' ../Data/allsutrani/*.htm > ../output/त्यक्तुं.html
grep -r 'शक्य' ../Data/allsutrani/*.htm > ../output/शक्य.html
grep -r 'संमत' ../Data/allsutrani/*.htm > ../output/संमत.html
grep -r 'निष्प्रयोजन' ../Data/allsutrani/*.htm > ../output/निष्प्रयोजन.html
grep -r 'पूर्वाचार्य' ../Data/allsutrani/*.htm > ../output/पूर्वाचार्य.html
grep -r 'व्याख्यान' ../Data/allsutrani/*.htm > ../output/व्याख्यान.html
grep -r 'वलम्बन' ../Data/allsutrani/*.htm > ../output/वलम्बन.html
grep -r 'आचार्य' ../Data/allsutrani/*.htm > ../output/आचार्य.html
grep -r 'श्रयणीय' ../Data/allsutrani/*.htm > ../output/श्रयणीय.html
grep -r 'मितरे' ../Data/allsutrani/*.htm > ../output/मितरे.html
grep -r 'त्यपरे' ../Data/allsutrani/*.htm > ../output/त्यपरे.html
grep -r 'वसेय' ../Data/allsutrani/*.htm > ../output/वसेय.html
grep -r 'त्यन्ये' ../Data/allsutrani/*.htm > ../output/त्यन्ये.html
grep -r 'नित्य' ../Data/allsutrani/*.htm > ../output/नित्य.html
grep -r 'द्रष्ट' ../Data/allsutrani/*.htm > ../output/द्रष्ट.html
grep -r 'सिद्धान्त' ../Data/allsutrani/*.htm > ../output/सिद्धान्त.html
grep -r 'धिक्' ../Data/allsutrani/*.htm > ../output/धिक्.html
grep -r 'सङ्ग्रह' ../Data/allsutrani/*.htm > ../output/सङ्ग्रह.html
grep -r 'प्रश्लेष' ../Data/allsutrani/*.htm > ../output/प्रश्लेष.html
grep -r 'मण्डूकप्लु' ../Data/allsutrani/*.htm > ../output/मण्डूकप्लुति.html
grep -r 'नभिधान' ../Data/allsutrani/*.htm > ../output/नभिधान.html
grep -r 'बहवः' ../Data/allsutrani/*.htm > ../output/बहवः.html
grep -r 'सौत्र' ../Data/allsutrani/*.htm > ../output/सौत्र.html
grep -r 'आर्ष' ../Data/allsutrani/*.htm > ../output/आर्ष.html
grep -r 'विनिगम' ../Data/allsutrani/*.htm > ../output/विनिगम.html
